  @Test
  void exception_catched_in_loop() throws Exception {
    CheckVerifier.newVerifier()
      .onFile("src/test/files/se/LoopExceptionField.java")
      .withChecks(seChecks())
      .withClassPath(SETestUtils.CLASS_PATH)
      .verifyIssues();
  }

