  private Object qix(Object o) throws MyException2 {
    Object result;
    try {
      foo(o);
    } catch (MyException1 e) {
      result = o;
    } finally {
      result = new Object();
    }
    return result;
  }

