  @Test
  void verify_unexpected_issue() {
    IssuableSubscriptionVisitor visitor = new FakeVisitor().withDefaultIssues().withIssue(4, "extra message");

    try {
      CheckVerifier.newVerifier()
        .onFile(FILENAME_ISSUES)
        .withCheck(visitor)
        .verifyIssues();
      Fail.fail("Should have failed");
    } catch (AssertionError e) {
      assertThat(e).hasMessage("Unexpected at [4]");
    }
  }

